/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Open a session: the access token, and the refresh token in its cookie.
         */
        post: operations["accounts_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revoke the session's refresh token and delete its cookie.
         */
        post: operations["accounts_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signed-in board member
         * @description The signed-in board member, as shown in the board space.
         */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew the session
         * @description Exchange the refresh cookie for a new access token and a new cookie.
         */
        post: operations["accounts_api_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the events
         * @description The events of the board, by page.
         *
         *     Upcoming events come the next first; past ones, like the whole list, the
         *     latest first. An event stays upcoming until the end of its last day.
         */
        get: operations["events_api_list_events"];
        put?: never;
        /**
         * Create an event
         * @description Record an event, with its programme and practical info.
         */
        post: operations["events_api_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an event
         * @description An event with all its content.
         */
        get: operations["events_api_detail"];
        /**
         * Update an event
         * @description Rewrite an event whole: its programme and practical info are replaced.
         */
        put: operations["events_api_update"];
        post?: never;
        /**
         * Delete an event
         * @description Delete an event, with its programme and practical info.
         */
        delete: operations["events_api_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/events/{event_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard of an event
         * @description The counts of an event's tabs, whole: a bounded aggregate, never paginated.
         */
        get: operations["dashboard_api_for_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the board members
         * @description The active board members, by name: the accounts that may lead an event.
         */
        get: operations["accounts_api_list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the notes of an event
         * @description The notes of an event, by page: the pinned ones first, then the latest,
         *     each with its replies.
         */
        get: operations["notes_api_list_notes"];
        put?: never;
        /**
         * Write a note
         * @description Record a note of the signed-in member, on an event or general.
         */
        post: operations["notes_api_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rewrite a note
         * @description Rewrite a note or a reply. Only its author finds it: anyone else gets a 404.
         */
        put: operations["notes_api_update"];
        post?: never;
        /**
         * Delete a note
         * @description Delete a note with its replies, or a reply. Only its author finds it.
         */
        delete: operations["notes_api_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/notes/{note_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply to a note
         * @description Record a reply of the signed-in member. A reply cannot be answered: 404.
         */
        post: operations["notes_api_create_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board overview
         * @description The dashboard's figures, whole: a bounded aggregate, never paginated.
         */
        get: operations["dashboard_api_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Report whether the service can answer, and which release is running.
         */
        get: operations["core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agenda overview
         * @description The categories of the agenda's events, and when the board last changed one.
         */
        get: operations["events_api_agenda_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/agenda.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendar feed of the agenda
         * @description Every published event, past ones included: a subscribed calendar keeps them.
         */
        get: operations["events_api_agenda_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the agenda
         * @description The published events to come, the next first, by page.
         */
        get: operations["events_api_list_agenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published event
         * @description A published event's page, past ones included, with the events that follow it.
         */
        get: operations["events_api_public_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/events/{slug}.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendar file of an event
         * @description A published event, to add to one's calendar.
         */
        get: operations["events_api_event_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenOut */
        AccessTokenOut: {
            /** Access */
            access: string;
        };
        /**
         * AgendaOut
         * @description What the site shows around its agenda.
         */
        AgendaOut: {
            /** Categories */
            categories: components["schemas"]["EventCategory"][];
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * BoardMemberOut
         * @description A board member as the board space names them, the lead of an event.
         *
         *     An account created without a name, such as with createsuperuser, is named
         *     after its email address.
         */
        BoardMemberOut: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Id */
            id: number;
            /** Last Name */
            last_name: string;
        };
        /**
         * BoardOverviewOut
         * @description What the board's dashboard shows.
         */
        BoardOverviewOut: {
            /** Upcoming Events */
            upcoming_events: components["schemas"]["EventItemOut"][];
            /** Upcoming Events Count */
            upcoming_events_count: number;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /**
         * EventCategory
         * @enum {string}
         */
        EventCategory: "children" | "meals" | "markets" | "games" | "festivities";
        /**
         * EventDashboardOut
         * @description What an event's page shows of its tabs: their counts.
         */
        EventDashboardOut: {
            /** Notes Count */
            notes_count: number;
        };
        /** EventFilters */
        EventFilters: {
            category?: components["schemas"]["EventCategory"] | null;
            /** Published */
            published?: boolean | null;
        };
        /**
         * EventIn
         * @description An event as the board writes it: whole, every key required.
         *
         *     A key left out never erases a value, the programme above all. The lists are
         *     given in display order and replace the previous ones. The values themselves
         *     are checked by the model, whose messages are in French.
         */
        EventIn: {
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at: string | null;
            /** Latitude */
            latitude: number | null;
            /** Lead */
            lead: number | null;
            /** Longitude */
            longitude: number | null;
            /** Practical Infos */
            practical_infos: components["schemas"]["PracticalInfoIn"][];
            /** Previous Edition */
            previous_edition: number | null;
            /** Price Detail */
            price_detail: string;
            /** Price Label */
            price_label: string;
            /** Programme */
            programme: components["schemas"]["ProgrammeItemIn"][];
            /** Published */
            published: boolean;
            /** Slug */
            slug: string;
            /** Start Label */
            start_label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Venue Address */
            venue_address: string;
            /** Venue Name */
            venue_name: string;
        };
        /**
         * EventItemOut
         * @description An event in a list.
         */
        EventItemOut: {
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at: string | null;
            /** Id */
            id: number;
            /** Published */
            published: boolean;
            /** Slug */
            slug: string;
            /** Start Label */
            start_label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Title */
            title: string;
            /** Venue Name */
            venue_name: string;
        };
        /**
         * EventOut
         * @description An event with all its content, in display order.
         */
        EventOut: {
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at: string | null;
            /** Id */
            id: number;
            /** Latitude */
            latitude: number | null;
            lead: components["schemas"]["BoardMemberOut"] | null;
            /** Longitude */
            longitude: number | null;
            /** Practical Infos */
            practical_infos: components["schemas"]["PracticalInfoOut"][];
            previous_edition: components["schemas"]["EventItemOut"] | null;
            /** Price Detail */
            price_detail: string;
            /** Price Label */
            price_label: string;
            /** Programme */
            programme: components["schemas"]["ProgrammeItemOut"][];
            /** Published */
            published: boolean;
            /** Slug */
            slug: string;
            /** Start Label */
            start_label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Venue Address */
            venue_address: string;
            /** Venue Name */
            venue_name: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: boolean;
            /** Release */
            release: string;
        };
        /** Input */
        Input: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /** Page Size */
            page_size?: number | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
        };
        /**
         * NoteIn
         * @description A note as a member writes it. Its values are checked by the model.
         */
        NoteIn: {
            /** Event */
            event: number | null;
            /** Pinned */
            pinned: boolean;
            tag: components["schemas"]["NoteTag"] | null;
            /** Text */
            text: string;
        };
        /**
         * NoteOut
         * @description A note of the board, with its replies.
         */
        NoteOut: {
            author: components["schemas"]["BoardMemberOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Editable */
            editable: boolean;
            /** Id */
            id: number;
            /** Pinned */
            pinned: boolean;
            /** Replies */
            replies: components["schemas"]["ReplyOut"][];
            tag: components["schemas"]["NoteTag"] | null;
            /** Text */
            text: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * NoteTag
         * @enum {string}
         */
        NoteTag: "minutes" | "budget" | "logistics";
        /**
         * NoteUpdateIn
         * @description A note or a reply rewritten by its author: a note stays on its event.
         *
         *     A reply keeps no tag and no pin: it is sent with neither.
         */
        NoteUpdateIn: {
            /** Pinned */
            pinned: boolean;
            tag: components["schemas"]["NoteTag"] | null;
            /** Text */
            text: string;
        };
        /** PagedBoardMemberOut */
        PagedBoardMemberOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["BoardMemberOut"][];
        };
        /** PagedEventItemOut */
        PagedEventItemOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["EventItemOut"][];
        };
        /** PagedNoteOut */
        PagedNoteOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["NoteOut"][];
        };
        /** PagedPublicEventItemOut */
        PagedPublicEventItemOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["PublicEventItemOut"][];
        };
        /**
         * PracticalInfoIcon
         * @enum {string}
         */
        PracticalInfoIcon: "people" | "home" | "check" | "info" | "warning" | "parking" | "food" | "accessibility";
        /** PracticalInfoIn */
        PracticalInfoIn: {
            icon: components["schemas"]["PracticalInfoIcon"];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** PracticalInfoOut */
        PracticalInfoOut: {
            icon: components["schemas"]["PracticalInfoIcon"];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** ProgrammeItemIn */
        ProgrammeItemIn: {
            /** Description */
            description: string;
            /**
             * Time
             * Format: time
             */
            time: string;
            /** Title */
            title: string;
        };
        /** ProgrammeItemOut */
        ProgrammeItemOut: {
            /** Description */
            description: string;
            /**
             * Time
             * Format: time
             */
            time: string;
            /** Title */
            title: string;
        };
        /** PublicEventFilters */
        PublicEventFilters: {
            category?: components["schemas"]["EventCategory"] | null;
        };
        /**
         * PublicEventItemOut
         * @description An event of the agenda.
         */
        PublicEventItemOut: {
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at: string | null;
            /** Price Detail */
            price_detail: string;
            /** Price Label */
            price_label: string;
            /** Slug */
            slug: string;
            /** Start Label */
            start_label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Title */
            title: string;
            /** Venue Name */
            venue_name: string;
        };
        /**
         * PublicEventOut
         * @description An event's page on the site, followed by the next events of the agenda.
         */
        PublicEventOut: {
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Next Events */
            next_events: components["schemas"]["PublicEventItemOut"][];
            /** Practical Infos */
            practical_infos: components["schemas"]["PublicPracticalInfoOut"][];
            /** Price Detail */
            price_detail: string;
            /** Price Label */
            price_label: string;
            /** Programme */
            programme: components["schemas"]["PublicProgrammeItemOut"][];
            /** Slug */
            slug: string;
            /** Start Label */
            start_label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Venue Address */
            venue_address: string;
            /** Venue Name */
            venue_name: string;
        };
        /** PublicPracticalInfoOut */
        PublicPracticalInfoOut: {
            icon: components["schemas"]["PracticalInfoIcon"];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** PublicProgrammeItemOut */
        PublicProgrammeItemOut: {
            /** Description */
            description: string;
            /**
             * Time
             * Format: time
             */
            time: string;
            /** Title */
            title: string;
        };
        /** ReplyIn */
        ReplyIn: {
            /** Text */
            text: string;
        };
        /**
         * ReplyOut
         * @description A reply to a note, in the order the replies were written.
         */
        ReplyOut: {
            author: components["schemas"]["BoardMemberOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Editable */
            editable: boolean;
            /** Id */
            id: number;
            /** Text */
            text: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationErrorItem */
        ValidationErrorItem: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /**
         * ValidationErrorOut
         * @description A 422 answer: one item per error, located under its field (core/errors.py).
         */
        ValidationErrorOut: {
            /** Detail */
            detail: components["schemas"]["ValidationErrorItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    accounts_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    accounts_api_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    events_api_list_events: {
        parameters: {
            query?: {
                category?: components["schemas"]["EventCategory"] | null;
                published?: boolean | null;
                period?: ("upcoming" | "past") | null;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEventItemOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    events_api_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    events_api_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    events_api_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    events_api_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_for_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDashboardOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    accounts_api_list_members: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedBoardMemberOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    notes_api_list_notes: {
        parameters: {
            query: {
                event: number;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedNoteOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    notes_api_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    notes_api_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    notes_api_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    notes_api_create_reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOverviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    events_api_agenda_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaOut"];
                };
            };
        };
    };
    events_api_agenda_feed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description iCalendar file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
        };
    };
    events_api_list_agenda: {
        parameters: {
            query?: {
                category?: components["schemas"]["EventCategory"] | null;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPublicEventItemOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    events_api_public_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    events_api_event_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description iCalendar file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
